fonts = "https://fonts.googleapis.com/css?family=IBM+Plex+Mono|IBM+Plex+Sans:400,500,700|Roboto+Condensed:400,400i,700,700i|Roboto:400,400i,500,500i,700,700i&subset=cyrillic,cyrillic-ext,greek,greek-ext,latin-ext,vietnamese"
to_sign = [
	"logger.dll",
	"logger64.dll",
]

[rust]
libs = ["logger"]
wasms = []

[csharp.packages]
"Newtonsoft.Json" = ["9.0.1", "net45"]

[csharp.plugins]
dll-call = { path = "plugins/dll-call" }
simple-io-plugin = { path = "plugins/simple-io-plugin" }
bootstrapper = { path = "plugins/bootstrapper", system_refs = ["System.IO.Compression", "System.IO.Compression.Filesystem"] }
file-reader-writer = { path = "plugins/file-reader-writer", package_refs = ["Newtonsoft.Json"] }
unbounded-request = { path = "plugins/unbounded-request", system_refs = ["System.Net.Http"] }
